// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace soundtest {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btn")]
		private MonoTouch.UIKit.UIButton btn {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btn")));
			}
			set {
				this.SetNativeField("btn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("sld")]
		private MonoTouch.UIKit.UISlider sld {
			get {
				return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("sld")));
			}
			set {
				this.SetNativeField("sld", value);
			}
		}
	}
}
